# Name of workflow
name: Update README

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    # Install node
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true

    - name: Update repo
      run: |-
        git pull

    - name: Update GitHub profile
      run: |-
        node update-readme.js
        cat README.md

    # Commit changes
    - name: Commit and push if changed
      run: |-
        git config --global user.email "readme-bot@example.com"
        git config --global user.name "README-bot"
        git diff --quiet || (git add README.md && git commit -m "Updated README")
        git push